version: '3.4'

services:
  mongo:
    image: mongo:latest
    command: --auth
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    container_name: 'mongo'
  
  node-service-one:
    depends_on:
      - mongo
    build:
      context: '../rakenduste-programmeerimine-TA-I-node'
    ports:
      - '3001:3000'
    volumes:
      - '../rakenduste-programmeerimine-TA-I-node:/home/node/app:delegated'
    command: 'run start'
    container_name: 'node-I'

  node-service-two:
    depends_on:
      - mongo
    build:
      context: '../rakenduste-programmeerimine-TA-II-node'
    ports:
      - '3002:3000'
    volumes:
      - '../rakenduste-programmeerimine-TA-II-node:/home/node/app:delegated'
    command: 'run start'
    container_name: 'node-II'
